[linux-lts]

source = "git"
git = "https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git"

branch = "linux-6.12.y"
prefix = "v"
include_regex = "v6.12.*"
exclude_regex = ".*(rc|alpha|beta).*"
